services:
  - type: web
    name: insurance-prediction-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "./start_main_app.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
    
  - type: web
    name: fairness-analysis-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "./start_fairness_app.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"